name: Build and Release Linux

on:
  push:
    tags:
      - 'v*' # Trigger when pushing version tags (e.g., v1.0.0)

jobs:
  build:
    name: Build Linux Binary
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Rust (assumes Zed uses Rust for its core)
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      # Step 3: Install dependencies (if any)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb1-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libatk1.0-dev libcairo2-dev libgdk-pixbuf2.0-dev libpango1.0-dev

      # Step 4: Build the project
      - name: Build Project
        run: |
          RUSTFLAGS="--cfg gles" cargo build --release

      # Step 5: Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zed-linux
          path: target/release/zed # Adjust the binary path if necessary

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download built artifact from the previous job
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: zed-linux

      # Step 2: Create a GitHub Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release contains the Linux build of Zed.
          artifacts: zed-linux
          token: ${{ secrets.GITHUB_TOKEN }}
